### ISSUE TITLE
Global Theme doesn't apply everywhere

### ISSUE THREAD

**Issue by Naverene** [ChrisTitusTech/linutil#165]
## Describe the bug
after applying "Global Dark Theme" KDE Settings is in light mode

## To Reproduce
open KDE Settings

## Expected behavior
KDE Settings to be in dark mode

## Screenshots
![image](https://github.com/user-attachments/assets/e91e359b-a456-4dc5-b53d-003f833bef14)

**Comment by nnyyxxxx** [comment]
I'll take a look.

**Comment by GreatNovaDragon** [comment]
Paraphrasing from #288 

The Global Theme script attempts to put use the qt6-theme controll application as the global QT-Theme (which you do outside of KDE), and in the qt6 controll application, then sets kvantum (an theme-engine) as its theme. Still correct.

Then for kvantum, a non-existent kvantum theme (Breeze) is set, which is the issue. Breeze in itself is the default theme-ing of KDE, which is why it might be sane to assume that this might exist as a kvantum theme. But kvantum is not an official KDE thing, and uses  different mechanisms to KDE/QT themeing, so Breeze does NOT support it.

**Comment by GreatNovaDragon** [comment]
To be precise, this line is at fault

https://github.com/ChrisTitusTech/linutil/blob/f46d3137b797c22cd917897544c3effde6eeb0cc/core/tabs/system-setup/global-theme.sh#L56C1-L56C13

The solution is to put something else than Breeze there. From the default themes that come with kvantum, i muse kvArc would be the best one. 

In the end, its a question of Chris's Preference what theme should be set

**Comment by nnyyxxxx** [comment]
will be fixed in #630
