### ISSUE TITLE
Takes a long time to run the command.

### ISSUE THREAD

**Issue by Kingproone** [ChrisTitusTech/linutil#170]
## Describe the bug
It can take upwards of 10 seconds for me to run the command.

## To Reproduce
run the following command and hit `Q` as soon as it reaches the tui:
$ `time curl -fsSL https://christitus.com/linux | sh`

## Expected behavior
Faster launchtimes.

## Screenshots

![Screenshot_20240817_130929](https://github.com/user-attachments/assets/6f4a9985-f751-4165-9c56-556c9d56acbc)

## Additional context
- EndeavourOS
- Download speeds for me are ~11 MB/s
- Linutil 08.01
- Ran the command a few times to see variance.

**Comment by SoapyDev** [comment]
I will address mainly how we can improve the weight of the binary, as it's to my knowledge the only thing we can affect when it comes to GitHub and distribution of the solution.

So far, I can only see 3 improvement that can be done, but they come at a cost or are not in line with the current vision of Chris.

------
1) Optimise the release profile for weight rather than speed. 

From my test, we can go from a binary of 2.2 MB to 1.5 MB, so about a 33% reduction in weight. I would expect a non-linear reduction in download time.

Ofc, we lose in performance, but so far even in debug mode, the TUI is really responsive.

I will submit the ticket for that one, as the cost in responsiveness is transparent to the user so far and this is really easy to implement and revert.


-------
2) Extract the commands from the binary and download them as needed.

That one, I am less a fan of as we are still in the process of finding a groove for how commands are shown/called and we are displacing waiting time in the preparation stage for waiting time at runtime. 

Plus the additional complexity of dealing with async calls and executing the scripts that would add to the weight of the binary. So maybe not a real reduction in weight for now. 

But, as the number of commands grow, it might become a needed solution at some point.


-------
3) Caching the binary

That one is straight out not aligned with Chris's vision so far. So, I can't imagine this being implemented in the near future. But I still wanted to put it out there, as caching is a solution for users repeating the process of calling the solution.

**Comment by jeevithakannan2** [comment]
@SoapyDev Reducing the binary size from 2.2 MB to 1.1 MB will not have any effect because as per @Kingproone , the average download speed is 11 MB/s so 2.2 MB binary should not be a issue here. I think it maybe a network latency due to geographical reasons. I think the more robust solution would be caching the binary by installing linutil.

**Comment by SoapyDev** [comment]
@jeevithakannan2, I agree. But as stated in #178, the only trade-off being done is at compile time, as the level is set to 3 to maintain performance. That way we still get reduced weight (1.3 MB) for the same performance. It might not fix this issue, but I don't see any reason to not move forward with it.

**Comment by jeevithakannan2** [comment]
Yeah I agree with you
