### ISSUE TITLE
Cache/download linutil to somewhere appropriate so the script executes quicker. 

### ISSUE THREAD

**Issue by Mxstyz** [ChrisTitusTech/linutil#243]
Or maybe give an option to cache/download the linutil within the menu or as parameters.

**Comment by adamperkowski** [comment]
i think it's better to package linutil (#333) for people who want to have it locally because when you run the "live" version with curl you still need to fetch the sctipt. having to download a script just to check if another one is already cached would be kinda pointless.

about the menu option, i think it's a good idea to be able to install linutil packages from within it (just like rofi for example)
