### ISSUE TITLE
Error downloading on aarch64 platform 

### ISSUE THREAD

**Issue by harbin-ctrl** [ChrisTitusTech/linutil#259]
## Describe the bug
I get an error downloading message when I run the script.
## To Reproduce
1. Run the script, get error

## Expected behavior
A nice menu
## Additional context
Aarch64 platform

**Comment by lj3954** [comment]
Linutil aarch64 builds were disabled in https://github.com/ChrisTitusTech/linutil/commit/468ef6799b5f77c81f2b2de3640288f634b0058b due to build failures when run in CI after #153. The build works just fine locally, so nobody really knows what the problem is right now. The start scripts are going to point you to an invalid release on aarch64 platforms until this is fixed.
