### ISSUE TITLE
uninstall? undo the changes ?

### ISSUE THREAD

**Issue by icf20** [ChrisTitusTech/linutil#260]
is there any way to uninstall or undo the changed made by this tool ? or any documentation on what is doing to know what to roll back

**Comment by cartercanedy** [comment]
nope, this is a prerelease tool. I'd recommend taking a look at the source scripts for the util(s) that you ran and try to revert that way

**Comment by ellenfel** [comment]
@icf20 
deleting the tool directly from home dir. deleting the link to `.bashrc` file  and reinstalling `.bashrc.bak` file.  did undo most if not all of the changes. iam still testing tho.

**Comment by cartercanedy** [comment]
> did undo most if not all of the changes.

This is true _*only if you run the bash prompt configuration*_ or any other tools that make modifications to `~/.bashrc`, and that's only true if the configuration was run only once. This advice will otherwise not be helpful and potentially confusing.

The most generalized advice for users trying to revert changes would be to examine the shell scripts of the tools that were run to understand and restore the original configuration, if possible.

**Comment by nnyyxxxx** [comment]
Yes, reverting is possible via taking a look at the scripts contents and undoing what the script did. As of now me and @adamperkowski and @lj3954 tried implementing this but found out that adding this would break a lot of systems via uninstalling certain deps. So this feature is not intended for now.
