### ISSUE TITLE
Arch server install fail laptop 

### ISSUE THREAD

**Issue by Grimmrp2** [ChrisTitusTech/linutil#310]
After running arch server install via the stable branch of linutil it fails at the end on lenovo laptop. 
![PXL_20240908_101303729](https://github.com/user-attachments/assets/bce24c33-de03-47a1-988c-5405e6b2427f)

Can anyone advise me how to grab a better log for a diagnosis?

Thanks

**Comment by Grimmrp2** [comment]
Ran again got same errors and some more pictures 
![PXL_20240908_152905103](https://github.com/user-attachments/assets/34096faa-b105-4b6f-83d3-92359b29fab8)
![PXL_20240908_152756262](https://github.com/user-attachments/assets/b4da1605-7d3a-4d8c-81bf-610e55870618)
![PXL_20240908_152945420](https://github.com/user-attachments/assets/472d9cb1-3bbb-49ba-8ebb-e9e7c4d86c3e)

**Comment by fam007e** [comment]
From the portion of the script you provided, the issue seems to arise in the `logo()` function around line 122-135, where it attempts to print the logo using `echo -ne`. Here's what could be happening:

## Potential Issues:

1. `echo -ne` Formatting:
The command echo -ne is used to print the string without adding a new line and enabling interpretation of backslash escapes (`-e`). However, if there is any issue with the interpretation or escaping of characters, this could result in the errors you're seeing (i.e., missing or unrecognized commands).

2. Whitespace or Unexpected Characters:
Sometimes, invisible or non-printable characters in the script (especially if copied from a different format) can cause errors when interpreted by the shell.

## Fixing Issues in script

### 1. Fix `echo -ne` Formatting Issue

The `echo -ne` command might be misinterpreting the special characters in the ASCII art. Instead, use a **heredoc** to print the ASCII art. Here’s the corrected version of the `logo` function.

```bash
logo () {
  cat << "EOF"
-------------------------------------------------------------------------
 **logo goes here**
-------------------------------------------------------------------------
        Please select preset setup settings for your system
-------------------------------------------------------------------------
EOF
}
```

### 2. Verify the Script for Invisible Characters

```sh
cat -A your_script.sh
```

### 3. Just remove the logo part from the script.

**Comment by nnyyxxxx** [comment]
It's already fixed on the latest release.

/close
